apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: cephblockpool-replicated
  namespace: openshift-storage
spec:
  compressionMode: none
  enableRBDStats: true
  erasureCoded:
    codingChunks: 0
    dataChunks: 0
  failureDomain: rack
  mirroring: 
    enabled: true
    mode: image  
  quotas: {}
  replicated:
    replicasPerFailureDomain: 1
    size: 3
    targetSizeRatio: 0.49
  statusCheck:
    mirror: {}
