kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managescc
rules:
  - verbs:
      - create
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints

