application:
  version: 2.0

wordpress:
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  mariadb:
    primary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
memcached:
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
mariadb:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
