wordpress:
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  mariadb:
    primary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
  memcached:
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
