application:
  version: 1.0

wordpress:
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  service:
    type: ClusterIP
  wordpressPassword: user
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  persistence:
    enabled: false
  mariadb:
    primary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
      persistence:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
memcached:
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
mariadb:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
