wordpress:
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  mariadb:
    primary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
memcached:
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
mariadb:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
