apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: coreos-iso-cdrom
spec:
  source:
    http:
      url: >-
        https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/latest/rhcos-live.x86_64.iso
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
    storageClassName: ocs-storagecluster-ceph-rbd
