apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hperedhat-viewer
  namespace: redhat-ods-applications
subjects:
- kind: User
  name: hpe_redhat
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hperedhat-admin
  namespace: mnist
subjects:
- kind: User
  name: hpe_redhat
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io