apiVersion: batch/v1
kind: Job
metadata:
  name: create-local-volumes
  namespace: redhat-ods-applications
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      serviceAccountName: jobs
      containers:
      - name: create-vol
        image: registry.redhat.io/openshift4/ose-cli:v4.11.0-202302061916.p0.g1928ac4.assembly.stream
        command:
         - /bin/sh
         - -c
         - oc -n snogpu debug node/snogpu -- chroot /host mkdir -m 777 /tmp/local-pv{1..3}
      restartPolicy: Never