apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan-ens224-1081-policy
spec:
  desiredState:
    interfaces:
      - description: VLAN 1081 using ens224
        ipv4:
          address:
            - ip: 10.6.81.198
              prefix-length: 24
          dhcp: false
          enabled: true
        name: ens224.1081
        state: up
        type: vlan
        vlan:
          base-iface: ens224
          id: 1081
      - description: VLAN 1085 using ens224
        ipv4:
          address:
            - ip: 10.6.85.198
              prefix-length: 24
          dhcp: false
          enabled: true
        name: ens224.1085
        state: up
        type: vlan
        vlan:
          base-iface: ens224
          id: 1085
  nodeSelector:
    kubernetes.io/hostname: ocp1-bm4nq-worker-zqffn
