apiVersion: v1
kind: Pod
metadata:
  name: setup-kasten
  namespace: kasten-io
spec:
  serviceAccountName: default
  restartPolicy: OnFailure
  containers:
    - name: cli
      image: 'quay.io/openshift/origin-cli'
      command:
            - /bin/bash
            - '-c'
      args:
            - >-
              curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

              VERIFY_CHECKSUM=false sh ./get_helm.sh            
              
              ./helm repo add kasten https://charts.kasten.io/
                            
              ./helm install k10 kasten/k10 --namespace=kasten-io --set scc.create=true --set route.enabled=true --set route.tls.enabled=true --set auth.tokenAuth.enabled=true

              oc annotate volumesnapshotclass ocs-storagecluster-cephfsplugin-snapclass k10.kasten.io/is-snapshot-class=true 
              
              oc annotate volumesnapshotclass ocs-storagecluster-rbdplugin-snapclass k10.kasten.io/is-snapshot-class=true            
