kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-kasten-install
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kasten-io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kasten-install
