kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-secret
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - list
    apiGroups:
      - 'networking.k8s.io'
    resources:
      - networkpolicies
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patch-volumesnapshotclasses
rules:  
  - verbs:
      - patch
    apiGroups:
      - 'snapshot.storage.k8s.io'
    resources:
      - volumesnapshotclasses
