kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-read-secret
  namespace: kasten-io  
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kasten-io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-secret
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-patch-volumesnapshotclasses
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kasten-io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-volumesnapshotclasses
