apiVersion: storage.hpe.com/v1
kind: HPECSIDriver
metadata:
  name: csi-driver
  namespace: hpe-csi-driver
spec:
  logLevel: info
  disable:
    alletra6000: false
    alletra9000: false
    nimble: false
    primera: false
  disableNodeConformance: false
  iscsi:
    chapPassword: ''
    chapUser: ''
  imagePullPolicy: IfNotPresent
  cspClientTimeout: 60
  disableNodeGetVolumeStats: false
  registry: quay.io
  kubeletRootDir: /var/lib/kubelet/