kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managescc
rules:
  - verbs:
      - create
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-hpecsidrivers
  namespace: hpe-csi-driver
rules:
  - verbs:
      - watch
      - list
      - get
      - create
      - patch
      - update
      - delete
    apiGroups:
      - storage.hpe.com
    resources:
      - hpecsidrivers

