apiVersion: v1
kind: Pod
metadata:
  name: imageregistry-enable
  namespace: openshift-machine-config-operator
spec:
  serviceAccountName: cluster-image-registry-operator
  restartPolicy: OnFailure
  containers:
        - name: cli
          image: 'quay.io/openshift/origin-cli'
          command:
            - /bin/bash
            - '-c'
          args:
            - >-
              oc patch configs.imageregistry.operator.openshift.io/cluster --type merge -p '{"spec":{"defaultRoute":true,"managementState":"Managed","storage":{"pvc":{"claim":"internal-registry-storage"}}}}'
