apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: internal-registry-storage
spec: 
  accessModes: 
    - ReadWriteMany
  resources: 
    requests: 
      storage: 100Gi
  storageClassName: ceph-fs...
