apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: vc-clusters-4-12-30
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/clusterset: vc
            openshiftVersion: 4.12.30
