apiVersion: v1
kind: Pod
metadata:
  name: set-default-sc
  namespace: openshift-storage
spec:
  serviceAccountName: ocs-operator
  restartPolicy: OnFailure
  containers:
        - name: cli
          image: 'quay.io/openshift/origin-cli'
          command:
            - /bin/bash
            - '-c'
          args:
            - >-
              while [[ true ]]; do oc get sc/ocs-storagecluster-ceph-rbd; if [[ $? -eq 0 ]]; then break; fi; sleep 10; done
              
              oc patch sc/ocs-storagecluster-ceph-rbd -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}' --type merge
              
              oc patch OCSInitialization ocsinit -n openshift-storage --type json --patch  '[{ "op": "replace", "path": "/spec/enableCephTools", "value": true }]'
              
