apiVersion: v1
kind: Pod
metadata:
  name: setup-submariner-labels
  namespace: openshift-machine-config-operator
spec:
  serviceAccountName: machine-config-daemon
  restartPolicy: OnFailure
  containers:
    - name: cli
      image: 'quay.io/openshift/origin-cli'
      command:
            - /bin/bash
            - '-c'
      args:
            - >- 
              for node in `oc get nodes | grep worker | awk '{print $1;}'`; do 
                 oc label node $node --overwrite=true submariner.io/gateway="true"
                 ip=`oc get node $node -o wide | awk '{if ($1!="NAME") print $7;}'`
                 oc annotate node $node --overwrite=true gateway.submariner.io/public-ip="$ip"
              done
