apiVersion: v1
kind: Pod
metadata:
  name: setup-submariner-labels
  namespace: default
spec:
  serviceAccountName: ocs-operator
  restartPolicy: OnFailure
  containers:
    - name: cli
      image: 'quay.io/openshift/origin-cli'
      command:
            - /bin/bash
            - '-c'
      args:
            - >- 
              oc patch volumesnapshotclass ocs-storagecluster-rbdplugin-snapclass --type merge -p '{"metadata":{"labels":{"velero.io/csi-volumesnapshot-class":"true"}}}'
              oc patch volumesnapshotclass ocs-storagecluster-cephfsplugin-snapclass --type merge -p '{"metadata":{"labels":{"velero.io/csi-volumesnapshot-class":"true"}}}
