apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-cluster-credentials
  namespace: open-cluster-management
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - namespace
  verbs:
  - watch
  - list
- apiGroups:
  - ""
  resourceNames:
  - baremetal
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-cluster-credentials
  namespace: open-cluster-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-cluster-credentials
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: hpe_redhat
