apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demos-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: 'https://api.bm*.redhat.hpecic.net:6443'
    - namespace: '*'
      server: 'https://api.vc*.redhat.hpecic.net:6443'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
