kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-configmap--user-ca-bundle-openshift-config
  namespace: openshift-config
rules:
  - verbs:
      - get
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - configmaps
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-configmap--user-ca-bundle-openshift-config-managed
  namespace: openshift-config-managed
rules:
  - verbs:
      - get
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - configmaps
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-secrets-configmaps
  namespace: openshift-dr-system
rules:
  - verbs:
      - get
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - ramen-dr-cluster-operator-config
  - verbs:
      - get
      - list
      - create
      - update
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
