kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bm2-odf-dr-edit
  namespace: bm2
subjects:
  - kind: ServiceAccount
    namespace: openshift-dr-system
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: get-secrets
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bm3-odf-dr-edit
  namespace: bm3
subjects:
  - kind: ServiceAccount
    namespace: openshift-dr-system
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: get-secrets
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-dr-system
  namespace: openshift-dr-system
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-configmap--user-ca-bundle-openshift-config-dr
  namespace: openshift-config
subjects:
  - kind: ServiceAccount
    namespace: openshift-dr-system
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edit-configmap--user-ca-bundle-openshift-config
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-secrets-configmaps-dr
  namespace: openshift-dr-system
subjects:
  - kind: ServiceAccount
    namespace: openshift-dr-system
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edit-secrets-configmaps
