kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-configmap--user-ca-bundle-openshift-config
  namespace: openshift-config
rules:
  - verbs:
      - get
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - configmap
    resourceNames:
      - user-ca-bundle
---      
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-secrets
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - secrets
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-secrets-configmaps
  namespace: openshift-dr-system
rules:
  - verbs:
      - get
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - configmap
    resourceNames:
      - ramen-dr-cluster-operator-config
  - verbs:
      - get
      - list
      - create
      - update
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - odr-s3secret-primary
      - odr-s3secret-secondary
