apiVersion: v1
kind: Pod
metadata:
  name: label-nodes
  namespace: default
spec:
  containers:
        - name: cli
          image: 'quay.io/openshift/origin-cli'
          command:
            - /bin/bash
            - '-c'
          args:
            - >-
              for node in `oc get nodes | grep worker | awk '{print $1;}'`; do 
                 oc label node $node cluster.ocs.openshift.io/openshift-storage=""; 
              done
