kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k10-admins
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: hpe_redhat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k10-admin
