apiVersion: apik10.kasten.io/v1alpha1
kind: K10
metadata:
  name: k10
  namespace: kasten-io
spec:
  scc:
    create: true
  route:
    enabled: true
    tls:
      enabled: true
  auth:
    tokenAuth:
      enabled: true
