apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.name }}
  labels:
    cloud: 'vSphere'
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: 'vc'
spec:
  baseDomain: redhat.hpecic.net
  clusterName: {{ .Values.cluster.name }}
  controlPlaneConfig:
    servingCertificates: {}
  provisioning:
    installConfigSecretRef:
      name: {{ .Values.cluster.name }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .Values.cluster.name }}-ssh-private-key
    imageSetRef:
       #quay.io/openshift-release-dev/ocp-release:4.12.30-multi
      name: img4.12.30-multi-appsub
  platform:
    vsphere:
      cluster: HIT_RedHat
      certificatesSecretRef:
        name: {{ .Values.cluster.name }}-vsphere-certs
      credentialsSecretRef:
        name: {{ .Values.cluster.name }}-vsphere-creds
      vCenter: hitvcenter.hybridit.hpecic.net
      datacenter: HIT_RedHat
      defaultDatastore: VV.HIT-RedHat
      network: 'Openshift'
  installAttemptsLimit: 1
  installed: false
  pullSecretRef:
    name: {{ .Values.cluster.name }}-pull-secret
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: generates
  namespace: {{ .Values.cluster.name }}
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: generates
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: copy-vcenter
  namespace: open-cluster-management
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.cluster.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: copy-vcenter
