apiVersion: v1
kind: Pod
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: Replace=true
  name: generate-secrets
spec:
  serviceAccountName: default
  restartPolicy: OnFailure
  containers:
    - name: cli
      image: 'quay.io/openshift/origin-cli'
      command:
        - /bin/bash
        - '-c'
      args:
        - |
          oc create -f /opt/pull-secret.yaml
          oc create -f /opt/install-config-secret.yaml
          oc create -f /opt/ssh-private-key.yaml
          oc create -f /opt/vsphere-creds.yaml
          oc create -f /opt/vsphere-certs.yaml
      volumeMounts:
        - name: data
          mountPath: /opt
  initContainers:
    - name: get-secret
      image: quay.io/openshift/origin-cli
      command:
        - /bin/bash
        - '-c'
      args:
        - |
          oc get secret vcenter -n open-cluster-management -o json > /opt/vcenter.json
          oc get configmap data-cm -n test-vc -o json > /opt/data-cm.json
      volumeMounts:
        - name: data
          mountPath: /opt
    - name: prepare-secrets
      image: quay.io/openshift/origin-tools
      command:
        - /bin/bash
        - '-c'
      args:
        - |
          username=`jq -r .data.username /opt/vcenter.json | base64 -d`
          password=`jq -r .data.password /opt/vcenter.json | base64 -d`
          pullSecret=`jq -r .data.pullSecret /opt/vcenter.json | base64 -d`
          ssh_publickey=`jq -r '.data."ssh-publickey"' /opt/vcenter.json | base64 -d`
          pullSecret_b64=`jq -r .data.pullSecret /opt/vcenter.json`
          ssh_privatekey_b64=`jq -r '.data."ssh-privatekey"' /opt/vcenter.json`
          cacertificate_b64=`jq -r .data.cacertificate /opt/vcenter.json`

          jq -r '.data."install-config.yaml"' /opt/data-cm.json > /opt/install-config.yaml
          sed -i "s/@username@/$username/g" /opt/install-config.yaml
          sed -i "s/@password@/$password/g" /opt/install-config.yaml
          sed -i "s/@pullSecret@/$pullSecret/g" /opt/install-config.yaml
          sed -i "s|@sshKey@|$ssh_publickey|g" /opt/install-config.yaml
          install_config_b64=`cat /opt/install-config.yaml | base64 -w 0`
          jq -r '.data."pull-secret.yaml"' /opt/data-cm.json | sed -e "s/@pullSecret-b64@/$pullSecret_b64/g" > /opt/pull-secret.yaml
          jq -r '.data."install-config-secret.yaml"' /opt/data-cm.json | sed -e "s/@install-config-b64@/$install_config_b64/g" > /opt/install-config-secret.yaml
          jq -r '.data."ssh-private-key.yaml"' /opt/data-cm.json | sed -e "s/@ssh-privatekey-b64@/$ssh_privatekey_b64/g" > /opt/ssh-private-key.yaml
          jq -r '.data."vsphere-creds.yaml"' /opt/data-cm.json | sed -e "s/@username@/$username/g" | sed -e "s/@password@/$password/g" > /opt/vsphere-creds.yaml
          jq -r '.data."vsphere-certs.yaml"' /opt/data-cm.json | sed -e "s/@cacertificate-b64@/$cacertificate_b64/g" > /opt/vsphere-certs.yaml
      volumeMounts:
        - name: data
          mountPath: /opt
  volumes:
    - name: data
      emptyDir: {}
