kind: ConfigMap
apiVersion: v1
metadata:
  name: data-cm
  namespace: {{ .Values.cluster.name }}
data:
  install-config.yaml: |
    apiVersion: v1
    metadata:
      name: {{ .Values.cluster.name }}
    baseDomain: redhat.hpecic.net
    controlPlane:
      hyperthreading: Enabled
      name: master
      replicas: 3
      platform:
        vsphere:
          cpus:  4
          coresPerSocket:  2
          memoryMB:  16384
          osDisk:
            diskSizeGB: 120
    compute:
    - hyperthreading: Enabled
      name: 'worker'
      replicas: 3
      platform:
        vsphere:
          cpus:  4
          coresPerSocket:  2
          memoryMB:  16384
          osDisk:
            diskSizeGB: 120
    platform:
      vsphere:
        vCenter: hitvcenter.hybridit.hpecic.net
        username: "@username@"
        password: "@password@"
        datacenter: HIT_RedHat
        defaultDatastore: VV.HIT-RedHat
        cluster: HIT_RedHat
        apiVIP: {{ .Values.cluster.vips.api }}
        ingressVIP: {{ .Values.cluster.vips.ingress }}
        network: 'Openshift'
    pullSecret: '@pullSecret@'
    sshKey: |-
      @sshKey@
    imageContentSources:
  pull-secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name:  {{ .Values.cluster.name }}-pull-secret
      namespace: {{ .Values.cluster.name }}
    data:
      .dockerconfigjson: @pullSecret-b64@
  install-config-secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name:  {{ .Values.cluster.name }}-install-config
      namespace:  {{ .Values.cluster.name }}
    type: Opaque
    data:
      install-config.yaml: @install-config-b64@
  ssh-private-key.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name:  {{ .Values.cluster.name }}-ssh-private-key
      namespace:  {{ .Values.cluster.name }}
    data:
      ssh-privatekey: @ssh-privatekey-b64@
    type: Opaque
  vsphere-creds.yaml: |
    apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name:  {{ .Values.cluster.name }}-vsphere-creds
      namespace:  {{ .Values.cluster.name }}
    stringData:
      username: @username@
      password: @password@
  vsphere-certs.yaml: |
    apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name:  {{ .Values.cluster.name }}-vsphere-certs
      namespace:  {{ .Values.cluster.name }}
    data:
      .cacert: @cacertificate-b64@
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: generates
  namespace: {{ .Values.cluster.name }}
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: generates
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: copy-vcenter
  namespace: open-cluster-management
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.cluster.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: copy-vcenter
