apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  annotations:
    "helm.sh/hook": post-install
  labels:
    cloud: vSphere
    name: {{ .Values.name }}
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: 'vc'
  name: {{ .Values.name }}
spec:
  hubAcceptsClient: true
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  annotations:
    "helm.sh/hook": post-install
  name: {{ .Values.name }}-worker
  namespace: {{ .Values.name }}
spec:
  clusterDeploymentRef:
    name: {{ .Values.name }}
  name: worker
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
  replicas: 3
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  annotations:
    "helm.sh/hook": post-install
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
spec:
  clusterName: {{ .Values.name }}
  clusterNamespace: {{ .Values.name }}
  clusterLabels:
    cloud: vSphere
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
