apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: post-install-cluster
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - git:
              directories:
                - path: applications/post-install/*
              repoURL: 'https://github.com/fdavalo/cluster-configuration'
              revision: main
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: development-clusters
  template:
    metadata:
      name: '{{name}}-post-install-{{path.basename}}'
    spec:
      destination:
        name: '{{clusterName}}'
        namespace: '{{path.basename}}'
      project: dev
      source:
        path: '{{path}}'
        repoURL: 'https://github.com/fdavalo/cluster-configuration'
        targetRevision: main
      syncPolicy:
        automated: {}
