apiVersion: v1
kind: Pod
metadata:
  name: project-templates
  namespace: openshift-config-operator
spec:
  serviceAccountName: openshift-config-operator
  containers:
        - name: cli
          image: 'quay.io/openshift/origin-cli'
          command:
            - /bin/bash
            - '-c'
          args:
            - >-
              oc patch project.config.openshift.io/cluster -p '{"spec":{"projectRequestTemplate":{"name":"project-request"}}}' --type merge
