apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero
  namespace: openshift-oadp
spec:
  backupLocations:
    - name: local
      velero:
        config:
          insecureSkipTLSVerify: 'true'
          profile: nooba
          region: us-east-1
          s3ForcePathStyle: 'true'
          s3Url: 'https://s3.openshift-storage.svc:443'
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: oadp-s3-backup-bucket-nooba
          prefix: local
        provider: aws
    - name: bm3
      velero:
        config:
          insecureSkipTLSVerify: 'false'
          profile: nooba
          region: us-east-1
          s3ForcePathStyle: 'true'
          s3Url: 'https://s3-openshift-storage.apps.bm3.redhat.hpecic.net'
        credential:
          key: cloud
          name: cloud-credentials-bm3
        default: true
        objectStorage:
          bucket: oadp-s3-backup-bucket-nooba
          prefix: bm3
          caCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiekNDQWxlZ0F3SUJBZ0lJTVc3SlNHWnF0V3d3RFFZSktvWklodmNOQVFFTEJRQXdKakVrTUNJR0ExVUUKQXd3YmFXNW5jbVZ6Y3kxdmNHVnlZWFJ2Y2tBeE5qUTNNamsxTWpVNU1CNFhEVEl6TURNd016QXhOVGcwTjFvWApEVEkxTURNd01qQXhOVGcwT0Zvd0p6RWxNQ01HQTFVRUF3d2NLaTVoY0hCekxtSnRNeTV5WldSb1lYUXVhSEJsClkybGpMbTVsZERDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHRNNFYrSXo5S0YKWGg4cjEwd0wwSURlMDl5UWRoWXJnSzNDNW9FWk51ckEya0hOS2pma2FTNUcrNkRaaWNITXdwYVVrblo5Sk9vbgpLMmVydUhxQ1ZKRnVhendSL0FZQ05QQnZSL1BBcGgySzlFL00xalcrOGRPc0FHN2lNNG9pSENMK1oxWDNOS0dYCnhZaWxMTFEzMFFhM3RxaDFRcmtRbGpJZXRzUDNncEhneGxPcVRlN3VOMHRoeFl2elBEVWhoTFdxaXFSdVN3bG4KOUJsbkJqNU9NQ3ZVSXJXTW9KbzdhbE1MOTgwN2t6b0JiNy9pOEs4elNFYm5XQ2pKb0FxYVF6UFJwZVErYjZ1ZwpuTjZXcG5rdFFnMnJZZnZqVkQrMTFPUlJ5MmtzQi80ckJWQ3ZMMnpmcWpQREkzN29WTFNRTTBtZHpDWmcwY25vCmFKKzhXUGlha29jQ0F3RUFBYU9CbnpDQm5EQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVIeitCdUl5elFSY3daV25LMEZkdgpseXVvN0VNd0h3WURWUjBqQkJnd0ZvQVVHZ1BtSGpDclBQemdSSGpKSEc1R0cxUlZjend3SndZRFZSMFJCQ0F3CkhvSWNLaTVoY0hCekxtSnRNeTV5WldSb1lYUXVhSEJsWTJsakxtNWxkREFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQWE3d21nL1RFdENXNElMUklLWkRLVTlUOHF1Ky9NaktkWjFIUDhEYU5Cdm1reFlacTF6ZndSeGtwRktYMwpNQmhNYjZzV0ZBQzZFbG1icHNZU2U4T0xHNDlmK2RXS2w0VHZSdkNjUWZNbnIyblJSd3I2Q2NqK1FzTFl4TVlHCkpqb3VZOUJ5akNDMkpQQ2RyV1pnU08vc0tnNlhoeWl0ZU5nVWRrZ0xHeUFoYlBTK1BHbVdlb1lkdDRqVUwrVy8KVHhFR1ZzZS9keVZieG5pY200aFJNclhGb2pLd1hUUGNIK3FMVVNaQXRPakU5ZkcwTEIxNEY4cXpkZHIrdGgyNwpJNUNydTF5TFlXMHl4TkNIQnlqWVZ0Ti9SZ2gzNWE4aDVQelJKQWROZWpNRlpnalFjeGVjNEd0ZWthV3BPaU5SCnQ3LzRsbHpsSWdlbGNGQ3drR0lmdDZ2SzFnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        provider: aws
    - name: bm2
      velero:
        config:
          insecureSkipTLSVerify: 'false'
          profile: nooba
          region: us-east-1
          s3ForcePathStyle: 'true'
          s3Url: 'https://s3-openshift-storage.apps.bm2.redhat.hpecic.net'
        credential:
          key: cloud
          name: cloud-credentials-bm2
        default: true
        objectStorage:
          bucket: oadp-s3-backup-bucket-nooba
          prefix: bm2
          caCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiekNDQWxlZ0F3SUJBZ0lJYUVMUE5TajZXSkV3RFFZSktvWklodmNOQVFFTEJRQXdKakVrTUNJR0ExVUUKQXd3YmFXNW5jbVZ6Y3kxdmNHVnlZWFJ2Y2tBeE5qYzJNamMzT1RZNE1CNFhEVEl6TURJeE16QTRORFl3T0ZvWApEVEkxTURJeE1qQTRORFl3T1Zvd0p6RWxNQ01HQTFVRUF3d2NLaTVoY0hCekxtSnRNaTV5WldSb1lYUXVhSEJsClkybGpMbTVsZERDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXBIL08rUHlJNGEKbGNicFp2RC9ucVdxbDBvYTdUSEd5L25ORm1maG1FV1RwQTdDTCtua295bktzeUk0NDBOdi9YNHpLd1ZWNTFLNwpKTUNlYzREeDBJWmQySUxFVFlPTEtxamZlWHZ2Y2Q0M2dyeG1SUnYzS3V4c1RjdGNrYW5YdTZGMStMeGkxQWFGCmNMamZYVXpkV0pkRE1HU0tmcjBFTHZERGhnTGpFV3JoMWVBMGhTR2pINVZBYVVvM1gvMGpncXI3dGJOZkYvc0sKeDV6aUdpanlVcFVra211eE5mY3hUcEVJc2JJTXU0T2NNT0VCMllTaEs1R1Q0aHJFOXN6ak5OK05xQUt6Z3pFbgpNMDRyemEvdmtkaENad0l1SWVaSWhKYjJVRU9zdVhNUXZBVXZ2NWZ0dXdlVm9aUzM0UVg2Qm1JZVdYU1A0SWxwCkd1cyt0K0FyYXNNQ0F3RUFBYU9CbnpDQm5EQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVqSjhOejFMbEUzTkExZWJsdklYZQpsam1FVXBvd0h3WURWUjBqQkJnd0ZvQVVYS3AxK0FoNDUwSVZ2bmJEVlRzdjFza0FUWVV3SndZRFZSMFJCQ0F3CkhvSWNLaTVoY0hCekxtSnRNaTV5WldSb1lYUXVhSEJsWTJsakxtNWxkREFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQU12NnozSElPMzRoc0VkaGZXc05lb1FLYUxLcEZLVmdIbFUvblkvU1VBd3UxR1FqUlJKKzBERjhma2VPRgpxMHF3aGZzMjkzZGxlWlNwYURVc0hSNTNsQWpTNUQ4OFVQYjExMC9BUlZnR0FwNjJucnVaZEM0YjJGU2Ywbmh3ClpGY1M1ZmsrdS9ZQ011RmNHenQvd216WEJFTzd1Ri9WcllSTmJ3UHlFaHk2ZHhQbmJEeTlBV3dsNFdheUdQM2UKSklzNmZMcnRtVjNzbTFxMW9qSEt2ak1nNDV0N1lzK1ZMM3krZFUrVXk4RDdMdkVjdjBZWDQvcGVZb1JtQmM2TQpMOU92ejE3ZW5JWmk0dTB4cUIzQnFuelhCMmpVRk1pUG5WZWYwMWNHMnlXS1d3ZDUzU29uMWVka0w5UDd1QnoxCm9EREdJczBuME8vZlhsa2Nod1dYNzJ2S3hnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        provider: aws
  configuration:
    restic:
      enable: true
    velero:
      defaultPlugins:
        - openshift
        - aws
        - csi
      featureFlags:
        - EnableCSI
  snapshotLocations:
    - velero:
        config:
          profile: nooba
          region: us-east-1
        provider: aws
  features:
    dataMover:
      credentialName: restic-secret
      enable: true
