apiVersion: v1
kind: Pod
metadata:
  name: setup-bucket-credentials
  namespace: openshift-oadp
spec:
  serviceAccountName: oadp-operator
  restartPolicy: OnFailure
  containers:
    - name: cli
      image: 'quay.io/openshift/origin-cli'
      command:
            - /bin/bash
            - '-c'
      args:
            - >-             
              while [[ true ]]; do oc -n openshift-oadp get secret oadp-s3-backup-bucket; if [[ $? -eq 0 ]]; then break; fi; sleep 10; done
              
              export BUCKET_ID=`oc -n openshift-oadp get secret oadp-s3-backup-bucket -o jsonpath="{.data.AWS_ACCESS_KEY_ID}" | base64 -d`
              
              export BUCKET_SECRET=`oc -n openshift-oadp get secret oadp-s3-backup-bucket -o jsonpath="{.data.AWS_SECRET_ACCESS_KEY}" | base64 -d`
                            
              echo "" | awk -v id=$BUCKET_ID -v key=$BUCKET_SECRET '{print "[bucket]"; print "aws_access_key_id="id; print "aws_secret_access_key="key; }'` > /tmp/cloud

              oc create secret generic oadp-s3-backup-bucket-velero --from-file=cloud=/tmp/cloud -n openshift-oadp

