apiVersion: v1
kind: Pod
metadata:
  name: setup-bucket-credentials
  namespace: openshift-oadp
spec:
  serviceAccountName: oadp-operator
  restartPolicy: OnFailure
  containers:
    - name: cli
      image: 'quay.io/openshift/origin-cli'
      command:
            - /bin/bash
            - '-c'
      args:
            - >-              
              while [[ true ]]; do oc -n openshift-oadp get secret oadp-s3-backup-bucket; if [[ $? -eq 0 ]]; then break; fi; sleep 10; done
              
              export BUCKET_ID=`oc -n openshift-oadp get secret oadp-s3-backup-bucket -o jsonpath="{.data.AWS_ACCESS_KEY_ID}" | base64 -d`
              
              export BUCKET_SECRET=`oc -n openshift-oadp get secret oadp-s3-backup-bucket -o jsonpath="{.data.AWS_SECRET_ACCESS_KEY}" | base64 -d`
              
              export cloud="[bucket]\naws_access_key_id=$BUCKET_ID\naws_secret_access_key=$BUCKET_SECRET"
              
              export cloud64=`echo -n "$cloud" | base64`

              create secret generic oadp-s3-backup-bucket-velero --from-literal=cloud=$cloud64 -n openshift-oadp

