apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero
  namespace: openshift-adp
spec:
  backupLocations:
    - velero:
        config:
          insecure_skip_tls_verify: 'true'
          profile: nooba
          region: us-east-1
          s3_force_path_style: 'true'
          s3_url: 'https://s3.openshift-storage.svc:443'
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: oadp-s3-backup-nooba-82581695-8bc2-410d-b89f-22e4f1a2eb55
          prefix: velero
        provider: aws
  configuration:
    restic:
      enable: true
    velero:
      defaultPlugins:
        - openshift
        - aws
  snapshotLocations:
    - velero:
        config:
          profile: nooba
          region: us-east-1
        provider: aws
