apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPolicy
metadata:
  name: odr-policy-5m
spec:
  drClusterSet:
    - name: bm2
      s3ProfileName: s3-primary
      region: hpecic
    - name: bm3
      s3ProfileName: s3-secondary
      region: hpecic
  replicationClassSelector: {}
  schedulingInterval: 5m
