apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  observabilityAddonSpec: {}
  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 20Gi
    receiveStorageSize: 20Gi
    ruleStorageSize: 1Gi
    storageClass: ocs-storagecluster-ceph-rbd
    storeStorageSize: 10Gi      
