apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: monitoring-alerts-pvc
  namespace: openshift-monitoring
spec:
  groups:
    - name: general.rules
      rules:
        - alert: PVCUseUpperThan85PC
          annotations:
            message: >
              PersistentVolumeClaim `{{ $labels.persistentvolumeclaim }}` in
              namespace `{{ $labels.namespace }}` over 85% used capacity.
          expr: >
            kubelet_volume_stats_used_bytes /
            kubelet_volume_stats_capacity_bytes > 0.85 and
            kubelet_volume_stats_used_bytes <=
            kubelet_volume_stats_capacity_bytes
          for: 10m
          labels:
            severity: critical
        - alert: PVCInodesUseUpperThan85PC
          annotations:
            message: >
              PersistentVolumeClaim `{{ $labels.persistentvolumeclaim }}` in
              namespace `{{ $labels.namespace }}` over 85% inodes used capacity.
          expr: >
            kubelet_volume_stats_inodes_used / kubelet_volume_stats_inodes >
            0.85 and kubelet_volume_stats_inodes_used <=
            kubelet_volume_stats_inodes
          for: 10m
          labels:
            severity: critical
