kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-create-objectbucketclaim
  namespace: open-cluster-management-observability
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: hpe_redhat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-objectbucketclaim
